import { useLocale } from './i18n';
export const legalPaths = ['/privacy-policy', '/terms', '/vendor-agreement'];
export function LegalLinks() {
  const {text} = useLocale();
  return <nav aria-label={text('Legal', 'Perundangan')} className="legal-links"><a href="/privacy-policy">{text('Privacy Policy', 'Dasar Privasi')}</a><a href="/terms">{text('Terms of Use', 'Syarat Penggunaan')}</a><a href="/vendor-agreement">{text('Vendor Agreement', 'Perjanjian Vendor')}</a></nav>;
}
export function LegalPage({path}: {path: string}) {
  const {text} = useLocale();
  const title = path === '/terms' ? text('Terms of Use', 'Syarat Penggunaan') : path === '/vendor-agreement' ? text('Vendor Agreement', 'Perjanjian Vendor') : text('Privacy Policy', 'Dasar Privasi');
  return <article className="surface"><h1>{title}</h1><p role="note">{text('Draft notice — pending legal review. Not a final agreement.', 'Notis draf — menunggu semakan undang-undang. Bukan perjanjian muktamad.')}</p><h2>{text('Purpose and scope', 'Tujuan dan skop')}</h2><p>{text('Warisan publishes heritage records and supports craft commerce. Personal information must be collected only for an explained purpose. Registration and booking consent must be recorded separately from optional marketing permission.', 'Warisan menerbitkan rekod warisan dan menyokong perdagangan kraf. Maklumat peribadi mesti dikumpulkan hanya untuk tujuan yang diterangkan. Persetujuan pendaftaran dan tempahan mesti direkodkan berasingan daripada kebenaran pemasaran pilihan.')}</p><h2>{text('Storage and choices', 'Storan dan pilihan')}</h2><p>{text('Language and versioned privacy preferences are stored in this browser for this domain. Optional analytics is off by default. Change or withdraw that preference using Privacy settings. No analytics integration is currently enabled.', 'Bahasa dan pilihan privasi berversi disimpan dalam pelayar ini untuk domain ini. Analitik pilihan dimatikan secara lalai. Ubah atau tarik balik pilihan tersebut melalui Tetapan privasi. Tiada integrasi analitik diaktifkan pada masa ini.')}</p><h2>{text('Before public launch', 'Sebelum pelancaran awam')}</h2><p>{text('The operator must publish its identity, contact channel, retention periods, data-recipient details, rights-request process, and reviewed vendor and transaction terms. These details are not yet finalised.', 'Pengendali mesti menerbitkan identiti, saluran hubungan, tempoh penyimpanan, butiran penerima data, proses permintaan hak, serta terma vendor dan transaksi yang disemak. Butiran ini belum dimuktamadkan.')}</p></article>;
}
