import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrandMark, LegalLinks, LegalPage, LanguageSwitcher, LocaleProvider, PrivacyBanner, Surface, useLocale } from '@warisan/ui';
import type { Artisan, CraftItem } from '@warisan/supabase-types';
import { DataError, getArtisan, getProvenanceItem, getPublishedCrafts, getVerifiedArtisans } from './data';
import '@warisan/ui/styles.css';
type LoadState = 'loading'|'ready'|'error';
function route(){return window.location.pathname.replace(/\/$/,'')||'/';}
function App(){return <LocaleProvider><AppContent/></LocaleProvider>}
function AppContent(){const {text}=useLocale();const path=route();if(['/privacy-policy','/terms','/vendor-agreement'].includes(path))return <Shell><LegalPage path={path}/></Shell>;if(path.startsWith('/provenance/'))return <Shell><ProvenancePage id={decodeURIComponent(path.slice(12))}/></Shell>;if(path.startsWith('/artisans/'))return <Shell><ArtisanPage id={decodeURIComponent(path.slice(9))}/></Shell>;return <Shell><RegistryPage/></Shell>}
function Shell({children}:{children:React.ReactNode}){const {text}=useLocale();return <main style={{maxWidth:'78rem',margin:'0 auto',padding:'1.5rem'}}><header className="site-header"><BrandMark domain="org"/><nav aria-label={text('Primary navigation','Navigasi utama')}><LanguageSwitcher/><a href="/#artisans">{text('Adiguru Kraf','Adiguru Kraf')}</a><a href="/#registry">{text('Registry','Daftar Warisan')}</a></nav></header>{children}<footer><LegalLinks/></footer><PrivacyBanner/></main>}
function ProvenancePage({id}:{id:string}){const {text}=useLocale();const [craft,setCraft]=useState<CraftItem>();const [state,setState]=useState<LoadState>('loading');useEffect(()=>{void getProvenanceItem(id).then(([x])=>{if(!x)throw new DataError('Not published');setCraft(x);setState('ready')}).catch(()=>setState('error'))},[id]);return <article className="detail-page"><a href="/#registry">← {text('Back to registry','Kembali ke daftar')}</a>{state==='loading'&&<p role="status">{text('Loading provenance record…','Memuatkan rekod asal-usul…')}</p>}{state==='error'&&<div role="alert" className="surface"><h1>{text('Record unavailable','Rekod tidak tersedia')}</h1></div>}{state==='ready'&&craft&&<><p className="provenance-label">PROVENANCE ID<br/>{craft.provenance_id}</p><h1>{craft.name}</h1><Surface><h2>{text('Registry record','Rekod daftar')}</h2><p>{craft.description}</p><dl><dt>{text('Fulfillment','Pemenuhan')}</dt><dd>{craft.is_local_pickup_only?text('Local pickup only','Ambil sendiri sahaja'):text('Eligible for delivery','Layak untuk penghantaran')}</dd><dt>{text('Reference price','Harga rujukan')}</dt><dd>MYR {Number(craft.price_myr).toFixed(2)}</dd></dl></Surface></>}</article>}
function ArtisanPage({id}:{id:string}){const {text}=useLocale();const [artisan,setArtisan]=useState<Artisan>();const [state,setState]=useState<LoadState>('loading');useEffect(()=>{void getArtisan(id).then(([x])=>{if(!x)throw new DataError('Not verified');setArtisan(x);setState('ready')}).catch(()=>setState('error'))},[id]);return <article className="detail-page"><a href="/#artisans">← {text('Back to Adiguru Kraf','Kembali ke Adiguru Kraf')}</a>{state==='loading'&&<p role="status">{text('Loading artisan record…','Memuatkan rekod artisan…')}</p>}{state==='error'&&<div role="alert" className="surface"><h1>{text('Artisan unavailable','Artisan tidak tersedia')}</h1></div>}{state==='ready'&&artisan&&<><p className="eyebrow">{artisan.craft_specialty} · {text('Verified artisan','Artisan disahkan')}</p><h1>{artisan.name}</h1><Surface><p>{artisan.bio}</p><p><strong>{text('Based in','Berpangkalan di')}:</strong> {artisan.location}</p></Surface></>}</article>}
function RegistryPage(){const {text}=useLocale();const [artisans,setArtisans]=useState<Artisan[]>([]);const [crafts,setCrafts]=useState<CraftItem[]>([]);const [state,setState]=useState<LoadState>('loading');const [error,setError]=useState('');async function load(){try{setState('loading');const [a,c]=await Promise.all([getVerifiedArtisans(),getPublishedCrafts()]);setArtisans(a);setCrafts(c);setState('ready')}catch(e){setError(e instanceof DataError?e.message:text('The registry is temporarily unavailable.','Daftar tidak tersedia buat sementara.'));setState('error')}}useEffect(()=>{void load()},[]);return <><section className="hero"><div><p className="eyebrow">{text('The trust layer','Lapisan kepercayaan')}</p><h1>{text('Craft carries memory.','Kraf membawa memori.')}</h1><p>{text('Warisan.org records the people, practices, and provenance behind Malaysian heritage craft.','Warisan.org merekodkan insan, amalan, dan asal-usul di sebalik kraf warisan Malaysia.')}</p></div><Surface><h2>{text('Verified, traceable, human.','Disahkan, boleh dijejak, berjiwa manusia.')}</h2><p>{text('Explore published records for Songket, Canting, Ukiran, Labu Sayong, and more.','Terokai rekod Songket, Canting, Ukiran, Labu Sayong, dan lain-lain.')}</p></Surface></section>{state==='loading'&&<p role="status" className="surface">{text('Loading the registry…','Memuatkan daftar…')}</p>}{state==='error'&&<div role="alert" className="surface"><h2>{text('Registry unavailable','Daftar tidak tersedia')}</h2><p>{error}</p><button className="button" onClick={()=>void load()}>{text('Try again','Cuba lagi')}</button></div>}{state==='ready'&&<><section id="artisans"><div className="section-heading"><h2>{text('Verified Adiguru Kraf','Adiguru Kraf Disahkan')}</h2><span>{artisans.length} {text('records','rekod')}</span></div><div className="registry-grid">{artisans.map(a=><Surface key={a.id}><p className="eyebrow">{a.craft_specialty}</p><h3>{a.name}</h3><p>{a.bio}</p><p><strong>{text('Based in','Berpangkalan di')}:</strong> {a.location}</p><span className="verified">✓ {text('Verified artisan','Artisan disahkan')}</span><p><a href={`/artisans/${a.id}`}>{text('View artisan record','Lihat rekod artisan')}</a></p></Surface>)}</div></section><section id="registry"><div className="section-heading"><h2>{text('Provenance registry','Daftar asal-usul')}</h2><span>{crafts.length} {text('records','rekod')}</span></div><div className="registry-grid">{crafts.map(c=><Surface key={c.id}><p className="provenance-label">PROVENANCE {c.provenance_id.slice(0,8).toUpperCase()}</p><h3>{c.name}</h3><p>{c.description}</p><p><strong>MYR {Number(c.price_myr).toFixed(2)}</strong>{c.is_local_pickup_only&&` · ${text('Local pickup only','Ambil sendiri sahaja')}`}</p><a href={`/provenance/${c.provenance_id}`}>{text('View registry record','Lihat rekod daftar')}</a></Surface>)}</div></section></>}</>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
