create extension if not exists pgcrypto;
create type public.app_role as enum ('customer','artisan','admin');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.app_role not null default 'customer', display_name text not null default '', pdpa_consent_date timestamptz, marketing_opt_in boolean not null default false, created_at timestamptz not null default now());
create table public.artisans (id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles(id) on delete set null, name text not null, craft_specialty text not null, bio text not null default '', location text not null, is_verified boolean not null default false, pdpa_consent_date timestamptz, marketing_opt_in boolean not null default false, created_at timestamptz not null default now());
create table public.craft_items (id uuid primary key default gen_random_uuid(), artisan_id uuid not null references public.artisans(id) on delete restrict, name text not null, description text not null default '', price_myr numeric(12,2) not null check (price_myr >= 0), provenance_id uuid not null unique default gen_random_uuid(), is_local_pickup_only boolean not null default false, is_published boolean not null default false, created_at timestamptz not null default now());
create table public.workshops (id uuid primary key default gen_random_uuid(), artisan_id uuid not null references public.artisans(id) on delete restrict, title text not null, description text not null default '', starts_at timestamptz not null, ends_at timestamptz not null, capacity integer not null check (capacity > 0), price_myr numeric(12,2) not null check (price_myr >= 0), is_published boolean not null default false, constraint workshops_valid_window check (ends_at > starts_at));
create table public.bookings (id uuid primary key default gen_random_uuid(), workshop_id uuid not null references public.workshops(id) on delete restrict, customer_id uuid not null references public.profiles(id) on delete restrict, quantity integer not null default 1 check (quantity > 0), status text not null default 'pending', pdpa_consent_date timestamptz, created_at timestamptz not null default now(), unique (workshop_id,customer_id));
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete restrict, status text not null default 'pending', total_myr numeric(12,2) not null default 0 check (total_myr >= 0), idempotency_key text unique, created_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, craft_item_id uuid not null references public.craft_items(id) on delete restrict, quantity integer not null check (quantity > 0), unit_price_myr numeric(12,2) not null check (unit_price_myr >= 0));
alter table public.profiles enable row level security;
alter table public.artisans enable row level security;
alter table public.craft_items enable row level security;
alter table public.workshops enable row level security;
alter table public.bookings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
create policy profiles_self on public.profiles for select using (id=auth.uid());
create policy artisans_public_verified on public.artisans for select using (is_verified=true or profile_id=auth.uid());
create policy craft_items_public on public.craft_items for select using (is_published=true);
create policy workshops_public on public.workshops for select using (is_published=true);
create policy bookings_own on public.bookings for select using (customer_id=auth.uid());
create policy bookings_insert_own on public.bookings for insert with check (customer_id=auth.uid());
create policy orders_own on public.orders for select using (customer_id=auth.uid());
create policy order_items_own on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid()));